// Data source: StepStone.de's server-rendered search results pages
// (https://www.stepstone.de/jobs/<query-slug>/in-<city-slug>). robots.txt disallows
// only the legacy /5/ergebnisliste.html path for User-agent: *; the current /jobs/...
// route is not disallowed for generic crawlers, so this does not carry the
// personal-use-only warning that linkedin-search/xing-search do.
//
// The card markup uses stable `data-at="job-item-*"` attributes for title/company/
// location/timeago, but everything else (CSS class names, exact DOM nesting depth) is
// generated by an Emotion/Next.js build and is NOT stable across cards — some cards
// wrap their text in an extra <div> (multi-line clamp), some don't. Field extraction
// is bounded per-card (never crosses into the next job-item's `data-at` marker) so a
// missing/differently-nested field yields null instead of silently borrowing the next
// field's text — confirmed against two real search pages during development (0 null
// company/location out of 50 cards across a Berlin and a Munich query).
//
// StepStone's own JSON XHR API (`/public-api/resultlist/`) 403s on a direct call
// (bot-protected, requires browser-issued session state) — the SSR HTML page is the
// only reliably fetchable source.
//
// KNOWN LIMITATION: the individual job-detail page
// (`/stellenangebote--<slug>--<id>-inline.html`) refused every fetch attempt during
// development with HTTP/2 connection resets (not a 403/429 — a protocol-level block,
// distinct from the search page's behavior). `detail` is implemented against the
// standard schema.org JobPosting JSON-LD pattern (the same one that works on
// Arbeitnow and is industry-common) as a best-effort, but this has **not** been
// live-verified against real StepStone output. See url-reference.md.

export const SEARCH_BASE = "https://www.stepstone.de/jobs"

export function writeError(error: string, code: string): void {
  process.stderr.write(JSON.stringify({ error, code }) + "\n")
}

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

/** Fetch HTML with exponential backoff on 429/5xx. Returns "" on a 404. */
export async function htmlFetch(url: string): Promise<string> {
  const maxRetries = 6
  let delay = 500
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    const response = await fetch(url, {
      headers: {
        "User-Agent": UA,
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "de-DE,de;q=0.9,en;q=0.8",
      },
      redirect: "follow",
      signal: AbortSignal.timeout(20000),
    })
    if (response.status === 429 || response.status >= 500) {
      if (attempt === maxRetries) {
        throw new Error(`Request failed: ${response.status} ${response.statusText}`)
      }
      const jitter = Math.floor(Math.random() * 500)
      await new Promise((r) => setTimeout(r, delay + jitter))
      delay = Math.min(delay * 2, 8000)
      continue
    }
    if (response.status === 404) return ""
    if (!response.ok) {
      throw new Error(`Request failed: ${response.status} ${response.statusText}`)
    }
    return response.text()
  }
  throw new Error("Request failed after max retries")
}

export interface JobCard {
  id: string
  title: string
  company: string | null
  location: string | null
  date: string | null
  timeagoRaw: string | null
  url: string
}

export interface JobDetail extends JobCard {
  description: string | null
  employmentType: string | null
  applyUrl: string | null
}

// Same named-entity set as arbeitnow-search: German postings routinely carry umlaut
// and typographic entities beyond the basic XML-escape set.
const NAMED_ENTITIES: Record<string, string> = {
  quot: '"',
  apos: "'",
  nbsp: " ",
  rsquo: "’",
  lsquo: "‘",
  rdquo: "”",
  ldquo: "“",
  hellip: "…",
  mdash: "—",
  ndash: "–",
  auml: "ä",
  ouml: "ö",
  uuml: "ü",
  Auml: "Ä",
  Ouml: "Ö",
  Uuml: "Ü",
  szlig: "ß",
  eacute: "é",
  egrave: "è",
}

function numericEntity(cp: number): string {
  return cp >= 0 && cp <= 0x10ffff ? String.fromCodePoint(cp) : ""
}

export function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&(\w+);/g, (m, name) => (name in NAMED_ENTITIES ? NAMED_ENTITIES[name] : m))
    .replace(/&#(\d+);/g, (_, dec) => numericEntity(parseInt(dec, 10)))
    .replace(/&#[xX]([0-9a-fA-F]+);/g, (_, hex) => numericEntity(parseInt(hex, 16)))
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
}

function stripTags(html: string): string {
  return html
    .replace(/<\s*br\s*\/?>/gi, "\n")
    .replace(/<\/(p|li|ul|ol|div|h\d)>/gi, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim()
}

/**
 * Remove invisible formatting characters. German job boards inject U+00AD SOFT
 * HYPHEN into titles and company names for typographic hyphenation; the string
 * renders identically but silently breaks cross-portal dedup, `/rank` keyword
 * matching, and any text copied into a CV. (Observed live on Xing; applied here
 * defensively since StepStone renders the same German typography.) NBSP becomes a
 * real space rather than vanishing, since it is genuine whitespace.
 */
export function stripInvisibles(text: string): string {
  return text.replace(/[\u00AD\u200B\u200C\u200D\uFEFF]/g, "").replace(/\u00A0/g, " ")
}

function clean(html: string): string {
  return stripInvisibles(decodeHtmlEntities(html)).trim()
}

/** ASCII-transliterate a German string for use in a StepStone URL path segment. */
export function germanSlugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/ä/g, "ae")
    .replace(/ö/g, "oe")
    .replace(/ü/g, "ue")
    .replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
}

export function buildSearchUrl(query: string | undefined, location: string | undefined, page: number): string {
  const parts = [SEARCH_BASE]
  if (query) parts.push(germanSlugify(query))
  const path = parts.join("/")
  const withLocation = location ? `${path}/in-${germanSlugify(location)}` : path
  return page > 1 ? `${withLocation}?page=${page}` : withLocation
}

/**
 * Extract text that follows an icon (`</svg></span>`) inside a `data-at="<key>"`
 * field, tolerating an optional line-clamp `<div>` wrapper and an optional inline
 * `<style>` block between the icon and the text. Bounded to never cross into the
 * next job-item's `data-at="job-item-` marker, so a card whose field doesn't match
 * this exact shape yields null instead of silently grabbing a neighboring field.
 */
function extractIconText(chunk: string, dataAtKey: string): string | null {
  const escaped = dataAtKey.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  const pattern = new RegExp(
    `${escaped}"(?:(?!data-at="job-item-)[\\s\\S])*?</svg></span>\\s*(?:<style[^>]*>[\\s\\S]*?</style>\\s*)?<span[^>]*data-genesis-element="TEXT"[^>]*>\\s*(?:<div[^>]*>)?\\s*([^<]+)`,
  )
  const m = chunk.match(pattern)
  return m ? clean(m[1]) || null : null
}

/**
 * Split the search-results HTML into per-job chunks. The anchor tag carrying both
 * the job's detail-page href (with its numeric ID) and `data-at="job-item-title"`
 * is the one reliable per-card boundary — unlike a bare `data-at="job-item-title"`
 * substring count, which also matches CSS attribute-selector rules embedded in
 * <style> blocks on the same page and over-counts.
 */
export function parseJobCards(html: string): JobCard[] {
  const anchorRe =
    /<a[^>]*href="(\/stellenangebote--[^"]+?--(\d+)-inline\.html)"[^>]*data-at="job-item-title"/g
  const starts: { index: number; href: string; id: string }[] = []
  let m: RegExpExecArray | null
  while ((m = anchorRe.exec(html)) !== null) {
    starts.push({ index: m.index, href: m[1], id: m[2] })
  }

  const results: JobCard[] = []
  for (let i = 0; i < starts.length; i++) {
    const chunk = html.slice(starts[i].index, i + 1 < starts.length ? starts[i + 1].index : html.length)
    const { href, id } = starts[i]

    let title: string | null = null
    const titleMatch = chunk.match(
      /data-at="job-item-title"[^>]*>(?:(?!data-at="job-item-)[\s\S])*?<div[^>]*>([^<]+)<\/div>/,
    )
    if (titleMatch) title = clean(titleMatch[1])
    if (!title) {
      // Fall back to deriving a readable title from the URL slug (always available).
      const slug = href.replace(/^\/stellenangebote--/, "").replace(/--\d+-inline\.html$/, "")
      title = slug.replace(/-/g, " ")
    }

    const company = extractIconText(chunk, 'data-at="job-item-company-name')
    const location = extractIconText(chunk, 'data-at="job-item-location')
    const timeMatch = chunk.match(/data-at="job-item-timeago"><time[^>]*>([^<]*)<\/time>/)
    const timeagoRaw = timeMatch ? clean(timeMatch[1]) : null

    results.push({
      id,
      title,
      company,
      location,
      date: timeagoRaw ? relativeGermanToISODate(timeagoRaw) : null,
      timeagoRaw,
      url: `https://www.stepstone.de${href}`,
    })
  }
  return results
}

/**
 * StepStone's search cards carry only a relative German time string ("vor 5 Tagen",
 * "vor 1 Woche", "vor 17 Stunden") — no machine-readable timestamp was found anywhere
 * in the page during investigation (confirmed: no `datetime` attribute on the <time>
 * tag, no ISO date in the surrounding markup). This is therefore an approximation,
 * not an exact posting date.
 */
export function relativeGermanToISODate(text: string, now: number = Date.now()): string | null {
  const m = text.match(/vor\s+(\d+)\s+(Stunde|Stunden|Tag|Tagen|Woche|Wochen|Monat|Monaten)/i)
  if (!m) {
    if (/heute/i.test(text)) return new Date(now).toISOString()
    if (/gestern/i.test(text)) return new Date(now - 86400000).toISOString()
    return null
  }
  const n = parseInt(m[1], 10)
  const unit = m[2].toLowerCase()
  let ms: number
  if (unit.startsWith("stunde")) ms = n * 3600000
  else if (unit.startsWith("tag")) ms = n * 86400000
  else if (unit.startsWith("woche")) ms = n * 7 * 86400000
  else ms = n * 30 * 86400000 // monat/monaten — approximate
  return new Date(now - ms).toISOString()
}

/** Convert a job-age in days to an approximate cutoff timestamp (ms since epoch). */
export function jobageToThresholdMs(days: number, now: number = Date.now()): number | null {
  if (!days || days <= 0 || days >= 9999) return null
  return now - days * 86400000
}

/**
 * Parse a job-detail page via its embedded schema.org JobPosting JSON-LD block.
 * UNVERIFIED against real StepStone output — see the module-level comment and
 * url-reference.md. Returns null if no matching JSON-LD is found, same as when the
 * page structure doesn't match what was expected.
 */
export function parseJobDetailFromHtml(html: string, url: string, id: string): JobDetail | null {
  const ldMatches = html.matchAll(/<script type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/gi)
  for (const ldMatch of ldMatches) {
    let parsed: any
    try {
      parsed = JSON.parse(ldMatch[1].trim())
    } catch {
      continue
    }
    const graph = Array.isArray(parsed) ? parsed : Array.isArray(parsed["@graph"]) ? parsed["@graph"] : [parsed]
    const posting = graph.find((n: any) => n && n["@type"] === "JobPosting")
    if (!posting) continue

    const title = typeof posting.title === "string" ? clean(posting.title) : "(untitled)"
    const company =
      posting.hiringOrganization && typeof posting.hiringOrganization.name === "string"
        ? clean(posting.hiringOrganization.name)
        : null
    const loc = posting.jobLocation
    const address = Array.isArray(loc) ? loc[0]?.address : loc?.address
    const location = address
      ? [address.addressLocality, address.addressRegion, address.addressCountry].filter(Boolean).join(", ") || null
      : null
    const description = typeof posting.description === "string" ? stripTags(clean(posting.description)) || null : null

    return {
      id,
      title,
      company,
      location,
      date: typeof posting.datePosted === "string" ? posting.datePosted : null,
      timeagoRaw: null,
      url,
      description,
      employmentType: typeof posting.employmentType === "string" ? posting.employmentType : null,
      applyUrl: typeof posting.url === "string" ? posting.url : url,
    }
  }
  return null
}
